---
- name: Push mission.json
  copy:
    src: "{{ PROJECT_PATH }}/software/applications/couscous/mission.json"
    dest: "/home/{{ PI_USERNAME }}"
    mode: "755"
- name: Restart couscous_app
  service:
    name: couscous_app.service
    state: restarted
